### ISSUE TITLE
Suporte para geração de Remessas para boletos registrados

### ISSUE THREAD

**Issue by alessandrogurgel** [BoletoSimples/boletosimples-ruby#10]
Pessoal, a empresa que trabalhou é cliente de vocês e gostaria de saber se a biblioteca suporta a geração de remessas para registro de boletos? Consigo fazer via o site boleto simples mas nao encontra na plataforma.

Caso nao haja suporte no momento, poderima me informar se esta no roadmap de vcs ?

Ainda, tem algum webservice disponivel para isso? Podem indicar documentacoes?

Obg

**Comment by kivanio** [comment]
Suporte sim.
Veja os exemplos: https://github.com/BoletoSimples/boletosimples-ruby-test/blob/master/index.rb#L390
