### ISSUE TITLE
Is oAuth2 obligatory?

### ISSUE THREAD

**Issue by fccoelho7** [BoletoSimples/boletosimples-ruby#11]
Hello guys!

In my current use case, we don't need to access any user's info. I'm trying to use the SDK only with the API KEY. Is it possible? I've set the ENV for it, and when trying to make some request I'm receiving a 401 error. Ps.: I'm using the sandbox environment.

Thanks!!

**Comment by kivanio** [comment]
No.
Just need token:
https://github.com/BoletoSimples/boletosimples-ruby-test/blob/master/index.rb#L14
Uncomment lines 13 and 14, set your token from https://api.boletosimples.com.br/authentication/token/

**Comment by fccoelho7** [comment]
@kivanio since I'm using Rails, do you suggest any place to add the config code?
