### ISSUE TITLE
Erro na criação do cliente 

### ISSUE THREAD

**Issue by carloslima18** [BoletoSimples/boletosimples-ruby#13]
Na chamada 
BoletoSimples::Customer.create({
                                                 person_name: "Joao da Silva", cnpj_cpf: "782.661.177-64", email: "cliente@bom.com",
                                                 address: "Rua quinhentos", city_name: "Rio de Janeiro",
                                                 state: "RJ", neighborhood: "bairro",
                                                 zipcode: "20071004", address_number: "111",  address_complement: "Sala 4",
                                                 phone_number: "2112123434", contact_person: "Nome do Contato",  truncated_address:"Rua quinhentos",  external_code:"12345678"
                                               })

recebo o seguinte retorno 
----------------------------------------------------------------------------
Response from the API must behave like a Hash or an Array (last JSON response was "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"pt\">\n<head>\n    <meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\"/>\n    <link rel=\"SHORTCUT ICON\" href=\"https://boletosimples.s3.amazonaws.com/maintenance/favicon.ico\"/>\n    <style type=\"text/css\" media=\"all\"></style>\n    <title>Boleto Simples: P\xC3\xA1gina n\xC3\xA3o encontrada</title>\n</head>\n<body>\n<div class=\"dialog\">\n\n    <div style=\"padding: 20px\" class=\"content\">\n\n        <p>\n            <img src=\"https://boletosimples.s3.amazonaws.com/maintenance/logo.png\"\n                 alt=\"Boleto Simples - https://boletosimples.com.br\" width=\"229\" height=\"39\"\n                 style=\"margin-top: 2em\"/>\n        </p>\n\n\n        <p style=\"margin-bottom: 3em;\"><strong>WOW! P\xC3\xA1gina N\xC3\xA3o Encontrada (Erro 404) :-(</strong></p>\n\n        <p>A p\xC3\xA1gina requisitada n\xC3\xA3o existe.</p>\n\n        <p>Voc\xC3\xAA pode ter usado um endere\xC3\xA7o antigo, ou ter digitado incorretamente na <strong>Barra de Endere\xC3\xA7o</strong> do seu\n            programa.</p>\n\n        <p>Por favor, verifique o endere\xC3\xA7o digitado ou tente <a href=\"https://boletosimples.com.br/\">nosso site</a></p>\n\n        <p>Caso voc\xC3\xAA esteja certo do endere\xC3\xA7o e este erro insista em aparecer, fique \xC3\xA0 vontade para nos <a\n                href=\"http://suporte.boletosimples.com.br/\">avisar pelo suporte</a>.</p>\n\n        <p>Desejando a sua compreens\xC3\xA3o,<br/>\n            <strong>Equipe do Boleto Simples</strong></p>\n\n    </div>\n\n    <div style='margin-top: 3em; padding: 20px' class=\"foot\">\n\n        <p style=\"margin: 0;\">Copyright\xC2\xA9 <a href=\"http://boletosimples.com.br\"\n         style=\"color: cornflowerblue; text-decoration: none\">Boleto Simples</a>.    </p>\n\n    </div>\n\n</div>\n</body>\n\n</html>\n")
--------------------------------------------------------

**Comment by kivanio** [comment]
Testou com nossos exemplos? 

https://github.com/BoletoSimples/boletosimples-ruby-test/blob/master/index.rb#L167

De qualquer forma estamos lançando uma versão atualizada hoje.

Vai precisar atualizar aí e mudar as configurações porque vai ter break changes
