### ISSUE TITLE
Erro em find BoletoSimples::BankBillet.find

### ISSUE THREAD

**Issue by carloslima18** [BoletoSimples/boletosimples-ruby#17]
Ao Atualiza a gema e fazer teste, ao executar o find do método, recebo o seguinte erro

0> self.boleto_simples_id
=> 8220255

0> BoletoSimples::BankBillet.find(self.boleto_simples_id)
Cache read: afbf0ddef9ffc775cddf61090d10e4125c491057
Cache read: afbf0ddef9ffc775cddf61090d10e4125c491057
Cache write: afbf0ddef9ffc775cddf61090d10e4125c491057
=> undefined method `[]' for nil:NilClass

**Comment by kivanio** [comment]
@carloslima18 mudou as configurações conforme https://github.com/BoletoSimples/boletosimples-ruby#configuração ?
Você chama o bloco de `configure` antes dessa chamada?

**Comment by carloslima18** [comment]
Faço faço sim. Inclusive o .all está funcionando
________________________________
De: Kivanio Barbosa ***@***.***>
Enviado: terça-feira, 18 de maio de 2021 10:21
Para: BoletoSimples/boletosimples-ruby ***@***.***>
Cc: carloslima18 ***@***.***>; Mention ***@***.***>
Assunto: Re: [BoletoSimples/boletosimples-ruby] Erro em find BoletoSimples::BankBillet.find (#17)


@carloslima18<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarloslima18&data=04%7C01%7C%7Cc5899294eb3948ac7c1408d919f7874c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637569373181469661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oqsxYqplqkCGaevUUoMGYj0oviOKxVsAYu1VAw9m3Ew%3D&reserved=0> mudou as configurações conforme https://github.com/BoletoSimples/boletosimples-ruby#configuração<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBoletoSimples%2Fboletosimples-ruby%23configura%25C3%25A7%25C3%25A3o&data=04%7C01%7C%7Cc5899294eb3948ac7c1408d919f7874c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637569373181479655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3WCn0AvK4CRa9Aqh%2BK%2FP1xuaDN8EcTqiimuaY6vtbfk%3D&reserved=0> ?
Você chama o bloco de configure antes dessa chamada?

**Comment by kivanio** [comment]
Tem um problema ao usar o cache, realmente.
Sem cache está funcionando.

**Comment by kivanio** [comment]
Tenta com a v 1.0.4
