### ISSUE TITLE
Método "cancel" não está sendo reconhecido V.1.0.4

### ISSUE THREAD

**Issue by carloslima18** [BoletoSimples/boletosimples-ruby#18]
Agora o Find está funcionando, no entanto o método cancel parou também. segue o script de teste.

...0> @bank_billet.cancel
=> undefined method `cancel' for #<BoletoSimples::BankBillet:0x00007fe3e74ae9f8>
Did you mean?  ...

**Comment by kivanio** [comment]
Você deve chamar direto, sem find:
@bank_billet = BoletoSimples::BankBillet.cancel(id: bank_billet_id)

Se baseie nos exemplos que deixamos aqui:
https://github.com/BoletoSimples/boletosimples-ruby-test
